export const FULFILLER_STATUS = {
  ALL: 'ALL',
  COMPLETED: 'COMPLETED',
  IN_PROGRESS: 'IN_PROGRESS',
  CANCELED: 'CANCELED',
  EXPIRED: 'EXPIRED',
  CANCELED_EXPIRED: 'CANCELED_EXPIRED',
  ORDERED: 'ORDERED',
  RECEIVED: 'RECEIVED',
  EXCEPTION: 'EXCEPTION',
};

export const SPECIMEN_RECEIVED_DATE_CONCEPT_UUID = "6234d61b-4c77-4af6-9bbb-533e44c03f24";

export const DEFAULT_TABLE_PAGE_SIZE = 10;
export const DEFAULT_ORDERS_BATCH_SIZE = 500;
