name: Deploy release

on:
  release:
    types: [ published ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Set up JDK 1.8 and Maven settings file
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: openmrs-repo-owa
          server-username: MAVEN_REPO_USERNAME
          server-password: MAVEN_REPO_PASSWORD

      - name: Deploy to Maven
        run: mvn deploy:deploy-file -Pdeploy-release
        env:
          MAVEN_REPO_USERNAME: mseaton
          MAVEN_REPO_PASSWORD: ${{ secrets.MAVEN_REPO_PASSWORD }}